### ISSUE TITLE
It Can't Open Terminal, and Fix GDrive Mount please.

### ISSUE THREAD

**Issue by FlushedCorn** [akuhnet/w-colab#12]
Tried XRDP version, and it just won't let me open terminal inside the rdp.
Throwing an error window:
`Failed to execute default Terminal Emulator. Input/output error.`

For GDrive, Use google-drive-ocaml-fuse for the mount method to fix it.

**Comment by FlushedCorn** [comment]
Nvm you can open terminal with right click desktop and run program, is this on purpose to hide the terminal (for some st*pid people who does mining) or it's an error/bug?

**Comment by akuhnet** [comment]
already update now
to open terminal go to Application > System > Xfce Terminal
Google Drive already fix thx
