### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by AKPR2007** [akuhnet/w-colab#2]
Hello @akuhnet

I want to tell you that colab windows VPS. is the thing I am wanting for a long time. The most slowing down in caused by using vnc protocol if you use remote desktop protocol or RDP hopefully it will fix 70% of the problem. Please finish the process soon. I am eagerly waiting for your response.

Thanks , AK PR

**Comment by akuhnet** [comment]
yeah I know, I will finish tomorrow with RDP, I'm testing on Kali Linux now and it worked

**Comment by AKPR2007** [comment]
> yeah I know, I will finish tomorrow with RDP, I'm testing on Kali Linux now and it worked

Hey please make it windows 8/10 Linux is not fun to use unless you're a pro. Take your time and continue your great work.

Thanks, AK PR
