### ISSUE TITLE
CPU 100% problem

### ISSUE THREAD

**Issue by AKPR2007** [akuhnet/w-colab#3]
Hey @akuhnet ,
Glad to see you working. Just wanted to say that opening any application even simple applications push the CPU usage to 100% . You can maybe try to upscale the CPU. It will also fix slowing down
Thanks, AK PR

**Comment by akuhnet** [comment]
Yes, because colab doesn't support Virtualization

**Comment by AKPR2007** [comment]
> Yes, because colab doesn't support Virtualization

Any way to enable vt or any colab alternative which supports vt ?

**Comment by akuhnet** [comment]
katacoda support vt

**Comment by AKPR2007** [comment]
> katacoda support vt

Hello, AKUH
Katacoda supports vt but the container is only for 1 hour. Plus katacoda has figured it out that people use it to create VPS so if you try to create any VPS using qemu-kvm + ngrok your environment expires instantly and when you refresh the page your ip address has been blocked by katacoda. I think they figured it out from the ngrok tunnel. GitHub had done the same thing for creating VPS. Last month I tried Chrome Remote Desktop on GitHub and it worked like a charm for 6h24m( you can check my rdp-chrome repo for more info) . So I think if we use Chrome Remote Desktop except ngrok this may/may not solve the katacoda problem. I would try myself but I don't know how to install Chrome Remote Desktop on qemu-kvm with shell.
Thanks, AKPR

**Comment by akuhnet** [comment]
yes I don't think so, I just added katacoda with ngrok

**Comment by AKPR2007** [comment]
> yes I don't think so, I just added katacoda with ngrok

Does it work for at least one hour without expiration

**Comment by akuhnet** [comment]
it runs 4 hours, and it's not a public terminal

**Comment by AKPR2007** [comment]
Oh ok , Then create a katacoda VPS tutorial plz
